python features_extractor.py -d ./Features/Incursion/implicit_mods/
python features_extractor.py -d ./Features/Incursion/corrupted_mods/
python features_extractor.py -d ./Features/Incursion/enchantment_mods/
python features_extractor.py -d ./Features/Incursion/unique_explicit_mods/
python rare_mod_handler.py -d ./Features/Incursion/rare_explicit_mods/
python features_extractor.py -d ./Features/Delve/implicit_mods/
python features_extractor.py -d ./Features/Delve/corrupted_mods/
python features_extractor.py -d ./Features/Delve/enchantment_mods/
python features_extractor.py -d ./Features/Delve/unique_explicit_mods/
python rare_mod_handler.py -d ./Features/Bestiary/rare_explicit_mods/
python features_extractor.py -d ./Features/Bestiary/implicit_mods/
python features_extractor.py -d ./Features/Bestiary/corrupted_mods/
python features_extractor.py -d ./Features/Bestiary/enchantment_mods/
python features_extractor.py -d ./Features/Bestiary/unique_explicit_mods/
python rare_mod_handler.py -d ./Features/Bestiary/rare_explicit_mods/
